name: gc_authenication
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gc_core:
    path: ../gc_core
  authenication_bloc:
    path: ../authenication_bloc
  flutter_form_builder: 6.1.0+1
  
  sizer: ^2.0.13
  country_pickers: ^2.0.0
  phone_number: ^0.12.0+1
  flutter_svg: ^0.22.0
  scroll_snap_list: ^0.8.2
  sms_autofill: ^2.0.1
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/icons/
publish_to: none
flutter_intl: # Use flutter pub run intl_utils:generate to generate localization
    enabled: true
    class_name: S # Optional. Sets the name for the generated localization class. Default: S
    arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
    output_dir: lib/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
