name: core
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #localized
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  #--- di ---
  get_it: ^7.1.3
  path_provider: ^2.0.2
  flutter_bloc: ^7.0.1
  intl_utils: ^2.3.0
  flutter_svg: ^0.22.0
  sizer: ^2.0.13
  flutter_form_builder: 6.1.0+1
  diacritic: ^0.1.3
  url_launcher: ^6.0.9
  permission_handler: ^8.1.4+2
  flutter_qr_reader: ^1.0.5
  image_picker: ^0.8.4+1
  #-- Network--
  flutter_cpnetworking_service: 0.1.6
  dio: ^4.0.0
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  photo_view: ^0.13.0
  gallery_saver: ^2.3.2

  # -- UIs
  flutter_spinkit: ^5.0.0
  another_flushbar: ^1.10.24

  awesome_dialog:
    path: ../library/awesome_dialog
  firebase_remote_config: ^1.0.2
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Bold.ttf
        - asset: fonts/GoogleSans-BoldItalic.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-MediumItalic.ttf
        - asset: fonts/GoogleSans-Regular.ttf
          style: normal
        - asset: fonts/GoogleSans-Italic.ttf
          style: italic
flutter_intl: # Use flutter pub run intl_utils:generate to generate localization
    enabled: true
    class_name: S # Optional. Sets the name for the generated localization class. Default: S
    main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
    arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
    output_dir: lib/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
